services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: gatekeeper
      POSTGRES_PASSWORD: gatekeeper
      POSTGRES_DB: gatekeeper
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gatekeeper"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    command: ["web"]
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg://gatekeeper:gatekeeper@postgres:5432/gatekeeper
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build: .
    command: ["worker"]
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg://gatekeeper:gatekeeper@postgres:5432/gatekeeper
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      SEED_ON_START: "false"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    # Scale horizontally: `docker compose up --scale worker=3`
    deploy:
      replicas: 1

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes:
      - ./infra/tempo/tempo.yaml:/etc/tempo/tempo.yaml:ro
    ports:
      - "3200:3200"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./infra/otel/config.yaml:/etc/otel/config.yaml:ro
    ports:
      - "4317:4317"
    depends_on:
      - tempo

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo

volumes:
  pgdata:
